# Generated by Django 4.1.3 on 2022-12-09 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_question_options_alter_quiz_options'),
        ('accounts', '0002_alter_userquizresult_correct_answers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquizresult',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to='quiz.quiz', verbose_name='Тест'),
        ),
    ]
